export const mockData = {
  featured: [
    {
      id: "f1",
      title: "Lovely Runner",
      type: "Drama Korea",
      year: 2024,
      genre: "Romantis, Fantasi",
      description:
        "Im Sol adalah penggemar berat Ryu Sun Jae, seorang idola K-pop yang meninggal secara tragis. Ketika dia mendapat kesempatan untuk kembali ke masa lalu, dia bertekad untuk mengubah takdir Sun Jae dan menyelamatkan hidupnya.",
      poster: "/placeholder.svg?height=450&width=300",
      backdrop: "/placeholder.svg?height=720&width=1280",
      bookNameLower: "lovely-runner",
      episodes: Array.from({ length: 16 }, (_, i) => ({
        number: i + 1,
        title: `Episode ${i + 1}`,
        duration: "1 jam 10 menit",
        thumbnail: "/placeholder.svg?height=90&width=160",
      })),
      cast: "Kim Hye Yoon, Byeon Woo Seok, Song Geon Hee",
      director: "Kim Tae Yeop",
      videoUrl: "/watch/lovely-runner",
    },
    {
      id: "f2",
      title: "Queen of Tears",
      year: 2024,
      genre: "Romantis, Drama",
      poster: "/placeholder.svg?height=450&width=300",
      bookNameLower: "queen-of-tears",
      videoUrl: "/watch/queen-of-tears",
    },
  ],
  trending: [
    {
      id: "t1",
      title: "Queen of Tears",
      year: 2024,
      genre: "Romantis, Drama",
      poster: "/placeholder.svg?height=450&width=300",
      bookNameLower: "queen-of-tears",
      videoUrl: "/watch/queen-of-tears",
    },
    {
      id: "t2",
      title: "A Time Called You",
      year: 2023,
      genre: "Romantis, Fantasi",
      poster: "/placeholder.svg?height=450&width=300",
      bookNameLower: "a-time-called-you",
      videoUrl: "/watch/a-time-called-you",
    },
    {
      id: "t3",
      title: "Moving",
      year: 2023,
      genre: "Aksi, Fantasi",
      poster: "/placeholder.svg?height=450&width=300",
      bookNameLower: "moving",
      videoUrl: "/watch/moving",
    },
    {
      id: "t4",
      title: "The Glory",
      year: 2023,
      genre: "Drama, Thriller",
      poster: "/placeholder.svg?height=450&width=300",
      bookNameLower: "the-glory",
      videoUrl: "/watch/the-glory",
    },
    {
      id: "t5",
      title: "Marry My Husband",
      year: 2024,
      genre: "Romantis, Drama",
      poster: "/placeholder.svg?height=450&width=300",
      bookNameLower: "marry-my-husband",
      videoUrl: "/watch/marry-my-husband",
    },
    {
      id: "t6",
      title: "Destined With You",
      year: 2023,
      genre: "Romantis, Fantasi",
      poster: "/placeholder.svg?height=450&width=300",
      bookNameLower: "destined-with-you",
      videoUrl: "/watch/destined-with-you",
    },
  ],
  koreanDramas: [
    {
      id: "k1",
      title: "Crash Landing on You",
      year: 2020,
      genre: "Romantis, Drama",
      poster: "/placeholder.svg?height=450&width=300",
      bookNameLower: "crash-landing-on-you",
      videoUrl: "/watch/crash-landing-on-you",
    },
    {
      id: "k2",
      title: "Itaewon Class",
      year: 2020,
      genre: "Drama",
      poster: "/placeholder.svg?height=450&width=300",
      bookNameLower: "itaewon-class",
      videoUrl: "/watch/itaewon-class",
    },
    {
      id: "k3",
      title: "Extraordinary Attorney Woo",
      year: 2022,
      genre: "Drama, Hukum",
      poster: "/placeholder.svg?height=450&width=300",
      bookNameLower: "extraordinary-attorney-woo",
      videoUrl: "/watch/extraordinary-attorney-woo",
    },
    {
      id: "k4",
      title: "Goblin",
      year: 2016,
      genre: "Romantis, Fantasi",
      poster: "/placeholder.svg?height=450&width=300",
      bookNameLower: "goblin",
      videoUrl: "/watch/goblin",
    },
    {
      id: "k5",
      title: "Hospital Playlist",
      year: 2020,
      genre: "Drama, Medis",
      poster: "/placeholder.svg?height=450&width=300",
      bookNameLower: "hospital-playlist",
      videoUrl: "/watch/hospital-playlist",
    },
    {
      id: "k6",
      title: "Reply 1988",
      year: 2015,
      genre: "Drama, Komedi",
      poster: "/placeholder.svg?height=450&width=300",
      bookNameLower: "reply-1988",
      videoUrl: "/watch/reply-1988",
    },
  ],
  chineseDramas: [
    {
      id: "c1",
      title: "The Untamed",
      year: 2019,
      genre: "Fantasi, Aksi",
      poster: "/placeholder.svg?height=450&width=300",
      bookNameLower: "the-untamed",
      videoUrl: "/watch/the-untamed",
    },
    {
      id: "c2",
      title: "Love Like The Galaxy",
      year: 2022,
      genre: "Romantis, Sejarah",
      poster: "/placeholder.svg?height=450&width=300",
      bookNameLower: "love-like-the-galaxy",
      videoUrl: "/watch/love-like-the-galaxy",
    },
    {
      id: "c3",
      title: "Reset",
      year: 2022,
      genre: "Thriller, Misteri",
      poster: "/placeholder.svg?height=450&width=300",
      bookNameLower: "reset",
      videoUrl: "/watch/reset",
    },
    {
      id: "c4",
      title: "Eternal Love",
      year: 2017,
      genre: "Romantis, Fantasi",
      poster: "/placeholder.svg?height=450&width=300",
      bookNameLower: "eternal-love",
      videoUrl: "/watch/eternal-love",
    },
    {
      id: "c5",
      title: "Word of Honor",
      year: 2021,
      genre: "Aksi, Sejarah",
      poster: "/placeholder.svg?height=450&width=300",
      bookNameLower: "word-of-honor",
      videoUrl: "/watch/word-of-honor",
    },
    {
      id: "c6",
      title: "The Long Ballad",
      year: 2021,
      genre: "Romantis, Sejarah",
      poster: "/placeholder.svg?height=450&width=300",
      bookNameLower: "the-long-ballad",
      videoUrl: "/watch/the-long-ballad",
    },
  ],
  japaneseDramas: [
    {
      id: "j1",
      title: "Alice in Borderland",
      year: 2020,
      genre: "Thriller, Sci-Fi",
      poster: "/placeholder.svg?height=450&width=300",
      bookNameLower: "alice-in-borderland",
      videoUrl: "/watch/alice-in-borderland",
    },
    {
      id: "j2",
      title: "Midnight Diner",
      year: 2016,
      genre: "Drama, Slice of Life",
      poster: "/placeholder.svg?height=450&width=300",
      bookNameLower: "midnight-diner",
      videoUrl: "/watch/midnight-diner",
    },
    {
      id: "j3",
      title: "Erased",
      year: 2017,
      genre: "Misteri, Thriller",
      poster: "/placeholder.svg?height=450&width=300",
      bookNameLower: "erased",
      videoUrl: "/watch/erased",
    },
    {
      id: "j4",
      title: "Good Morning Call",
      year: 2016,
      genre: "Romantis, Komedi",
      poster: "/placeholder.svg?height=450&width=300",
      bookNameLower: "good-morning-call",
      videoUrl: "/watch/good-morning-call",
    },
    {
      id: "j5",
      title: "Terrace House",
      year: 2019,
      genre: "Reality Show",
      poster: "/placeholder.svg?height=450&width=300",
      bookNameLower: "terrace-house",
      videoUrl: "/watch/terrace-house",
    },
    {
      id: "j6",
      title: "My Husband Won't Fit",
      year: 2019,
      genre: "Drama, Romantis",
      poster: "/placeholder.svg?height=450&width=300",
      bookNameLower: "my-husband-wont-fit",
      videoUrl: "/watch/my-husband-wont-fit",
    },
  ],
  varietyShows: [
    {
      id: "v1",
      title: "Running Man",
      year: 2010,
      genre: "Variety Show",
      poster: "/placeholder.svg?height=450&width=300",
      bookNameLower: "running-man",
      videoUrl: "/watch/running-man",
    },
    {
      id: "v2",
      title: "2 Days & 1 Night",
      year: 2007,
      genre: "Variety Show",
      poster: "/placeholder.svg?height=450&width=300",
      bookNameLower: "2-days-1-night",
      videoUrl: "/watch/2-days-1-night",
    },
    {
      id: "v3",
      title: "Knowing Bros",
      year: 2015,
      genre: "Variety Show",
      poster: "/placeholder.svg?height=450&width=300",
      bookNameLower: "knowing-bros",
      videoUrl: "/watch/knowing-bros",
    },
    {
      id: "v4",
      title: "Street Woman Fighter",
      year: 2021,
      genre: "Reality Competition",
      poster: "/placeholder.svg?height=450&width=300",
      bookNameLower: "street-woman-fighter",
      videoUrl: "/watch/street-woman-fighter",
    },
    {
      id: "v5",
      title: "I Live Alone",
      year: 2013,
      genre: "Reality Show",
      poster: "/placeholder.svg?height=450&width=300",
      bookNameLower: "i-live-alone",
      videoUrl: "/watch/i-live-alone",
    },
    {
      id: "v6",
      title: "New Journey to the West",
      year: 2015,
      genre: "Variety Show",
      poster: "/placeholder.svg?height=450&width=300",
      bookNameLower: "new-journey-to-the-west",
      videoUrl: "/watch/new-journey-to-the-west",
    },
  ],
}

export const mockMovieData = {
  pageProps: {
    tabData: ["1-50", "51-57"],
    bookInfo: {
      originalBookId: "41000111541",
      bookName: "Menelusuri Jejak Cinta",
      cover: "https://sres.dramaboxdb.com/data/cppartner/4x1/41x0/410x0/41000113270/41000113270.jpg@w=240&h=320",
      viewCount: 13214,
      followCount: 238353,
      introduction: "Demi mendapatkan uang bayaran untuk kuliah, Ella Reed terpaksa menerima tawaran kencan semalam dengan Sebastian Harrington, seorang milyarder berpengaruh dari Harrington Group yang mewarisi gen infertilitas dari keluarga. Saat Sebastian mengetahui Ella ternyata hamil anak kembar, Sebastian melakukan segala cara untuk melindungi dan memastikan kehamilan Ella berjalan lancar demi mendapatkan ahli waris yang telah lama diidam-idamkannya.",
      chapterCount: 57,
      labels: ["Family Bonds", "Secret Baby"],
      tags: ["Family Bonds", "Secret Baby"],
      typeTwoIds: [447],
      typeTwoNames: ["Romansa"],
      typeTwoList: [{
        id: 447,
        name: "Romansa",
        replaceName: "romansa"
      }],
      language: "BAHASA_INDONESIA",
      typeTwoName: "Romansa",
      simpleLanguage: "in",
      bookNameEn: "Carrying-His-Babies-Stealing-His-Heart",
      bookNameLower: "carrying-his-babies-stealing-his-heart"
    },
    recommends: [
      {
        originalBookId: "41000113005",
        bookName: "Jantungku Hanya Berdetak Untukmu",
        cover: "https://sres.dramaboxdb.com/data/cppartner/4x1/41x0/410x0/41000114328/41000114328.jpg@w=240&h=320",
        viewCount: 18225,
        followCount: 56976,
        introduction: "Arabella datang ke rumah Killian, seorang bos mafia, untuk menjadi pengasuh bagi Angela, keponakan Killian. Killian yang awalnya kurang setuju Arabella jadi pengasuh, terpaksa menyetujuinya karena permintaan Angela. Seiring berjalannya waktu, Arabella semakin terlibat dalam kehidupan mafia yang penuh kekerasan dan kejahatan, tapi dia pun semakin jatuh hati pada Killian. Akankah cinta mereka mampu bertahan di tengah konflik keluarga dan kejahatan yang semakin meningkat?",
        chapterCount: 53,
        labels: ["Forbidden Love", "Family Intrigue"],
        tags: ["Forbidden Love", "Family Intrigue"],
        typeTwoIds: [447],
        typeTwoNames: ["Romansa"],
        typeTwoList: [{
          id: 447,
          name: "Romansa",
          replaceName: "romansa"
        }],
        language: "BAHASA_INDONESIA",
        typeTwoName: "Romansa",
        simpleLanguage: "in",
        bookNameEn: "His-Sweet-Bella",
        bookNameLower: "his-sweet-bella"
      }
    ]
  }
}

// Helper function to get mock data for a specific movie
export function getMockMovieData(originalBookId: string, bookNameLower: string) {
  // In a real implementation, you would fetch from the API
  // For now, we'll return the mock data
  return mockMovieData;
}
